### ISSUE TITLE
Doesn't work well with dark mode

### ISSUE THREAD

**Issue by thelazyoxymoron** [mochar/logseq-incremental-blocks#1]
Thank you for this amazing plugin. I've just been playing around with this and haven't yet gotten to experience the entire functionality. However I noticed that the inline block for scheduling due was not visible in dark mode. Attaching a screenshot.

<img width="330" alt="Screenshot 2024-08-28 at 5 59 30 PM" src="https://github.com/user-attachments/assets/3160f333-63c1-4a83-80fc-460c1b17d4c1">

Just a minor nitpick though. I'm excited to spend a few days working with this plugin into my workflow.

**Comment by mochar** [comment]
Thanks for trying the plugin out! Not a minor nitpick at all, I will try to get it looking better with dark mode asap. 

You will definitely find more bugs along the way so please do keep reporting them ;-)

**Comment by mochar** [comment]
Hi @thelazyoxymoron sorry for the wait, I have added better support for dark move now, [here](https://github.com/mochar/logseq-incremental-blocks/releases/tag/v0.0.2). Let me know if you would like anything changed
