### ISSUE TITLE
The plugin seems not work with the lastest version of logseq (0.10.9)

### ISSUE THREAD

**Issue by luohc2004** [mochar/logseq-incremental-blocks#5]
It's a great idea to set up a increamental reading system via Logseq! But I met some problem when try to learning IR with logseq by your genious plugin. The problem is that logseq stuck to non-response when the "IB" button  clicked (as blow). I have to taskkill logseq to quit when it refuse to response.
![image](https://github.com/user-attachments/assets/cf6b5765-b134-4faa-b181-919f3c21f472)

My logseq version: 0.10.9.
![image](https://github.com/user-attachments/assets/a290b2d8-e0a9-4d05-b61d-6608b623c9cc)

**Comment by mochar** [comment]
Hi thanks for trying it out! Before you click on the button, can you open the console in logseq with ctrl-shift-i, and then after clicking it see if something pops up there? That will allow me to figure out what might be going wrong. Thnx!

**Comment by luohc2004** [comment]
> Hi thanks for trying it out! Before you click on the button, can you open the console in logseq with ctrl-shift-i, and then after clicking it see if something pops up there? That will allow me to figure out what might be going wrong. Thnx!

Thanks for replying! I found it may causeed by my fault. Maybe I just loaded the worng version of plugin(0.0.1) instead of (0.0.5). The problem does not appear again after I substitute the folder with new version. Ps. The version  show in plugin interface may not right as follow:

![image](https://github.com/user-attachments/assets/17369cf5-5963-4172-83b9-b3e9d1d92a69)

**Comment by mochar** [comment]
Oh yes I will try to fix that. Please share your thoughts about the plugin when you have any!

**Comment by GrittyB** [comment]
I have the same problem. It works in 0.0.4 but not in 0.0.5.
![CleanShot 2024-11-14 at 11  11 46@2x](https://github.com/user-attachments/assets/04afef93-b77f-4cf7-a466-dcdcf24aeccc)

**Comment by mochar** [comment]
@GrittyB When does this happen? And are there any other messages in the console?
